# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.234.0.5491
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
