# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: FilesCommunity.Files
PackageVersion: 2.4.33
PackageLocale: en-US
Publisher: Files Community
PublisherSupportUrl: https://github.com/files-community/Files/issues
PrivacyUrl: https://github.com/files-community/Files/blob/main/Privacy.md
Author: Files Community
PackageName: Files
PackageUrl: https://files.community/
License: MIT
LicenseUrl: https://github.com/files-community/Files/blob/main/LICENSE
Copyright: Copyright (c) 2023 Files Community
CopyrightUrl: https://github.com/files-community/Files/blob/main/LICENSE
ShortDescription: Files is a file manager that lets you easily organize content on your device. Robust multitasking experiences, helpful tags, and deep integrations add to an intuitive design.
Tags:
- archive
- file-manager
- tabs
- zip
Documentations:
- DocumentLabel: Product Documentation
  DocumentUrl: https://files.community/docs
ManifestType: defaultLocale
ManifestVersion: 1.4.0
