# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: xpipe-io.xpipe
PackageVersion: 1.5.2
PackageLocale: en-US
Publisher: XPipe-io
PublisherUrl: https://github.com/xpipe-io
PublisherSupportUrl: https://github.com/xpipe-io/xpipe/issues
Author: crschnick
PackageName: XPipe
PackageUrl: https://github.com/xpipe-io/xpipe
License: Apache License 2.0
LicenseUrl: https://github.com/xpipe-io/xpipe/blob/master/LICENSE.md
ShortDescription: A brand-new shell connection hub and remote file manager
Description: XPipe is a new type of shell connection hub and remote file manager that allows you to access your entire sever infrastructure from your local machine. It works on top of your installed command-line programs that you normally use to connect and does not require any setup on your remote systems.
Moniker: xpipe
Tags:
- remote
ReleaseNotesUrl: https://github.com/xpipe-io/xpipe/blob/master/dist/changelogs/1.5.2.md
Icons:
- IconUrl: https://github.com/xpipe-io/xpipe/blob/master/dist/logo/ico/logo_256x256.png
  IconFileType: png
  IconResolution: 256x256
- IconUrl: https://github.com/xpipe-io/xpipe/blob/master/dist/logo/ico/logo_16x16.png
  IconFileType: png
  IconResolution: 16x16
ManifestType: defaultLocale
ManifestVersion: 1.5.0
